### Passo 1 - Importar Arquivos e Bibliotecas

In [5]:
!pip install pandas

Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\anaconda\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [16]:
#importar bibliotecas
import pandas as pd
import win32com.client as win32
import pathlib

In [10]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [2]:
#importar bases de dados
emails = pd.read_excel(r'Bases de Dados\Emails.xlsx')
lojas = pd.read_csv(r'Bases de Dados\lojas.csv', encoding='latin1', sep=';')
vendas = pd.read_excel(r'Bases de Dados\Vendas.xlsx')
display(emails)
display(lojas)
display(vendas)

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,pythonimpressionador+helena@gmail.com
1,Shopping Midway Mall,Alice,pythonimpressionador+alice@gmail.com
2,Norte Shopping,Laura,pythonimpressionador+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,pythonimpressionador+manuela@gmail.com
4,Shopping União de Osasco,Valentina,pythonimpressionador+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,pythonimpressionador+sophia@gmail.com
6,Rio Mar Recife,Isabella,pythonimpressionador+isabella@gmail.com
7,Salvador Shopping,Heloisa,pythonimpressionador+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,pythonimpressionador+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,pythonimpressionador+julia@gmail.com
10,Ribeirão Shopping,Lorena,pythonimpressionador+lorena@gmail.com
11,Shopping Morumbi,Livia,pythonimpressionador+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,pythonimpressionador+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,pythonimpressionador+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,pythonimpressionador+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,pythonimpressionador+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,pythonimpressionador+arthur@gmail.com
17,Shopping Recife,Heitor,pythonimpressionador+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,pythonimpressionador+bernardo@gmail.com
19,Shopping SP Market,Davi,pythonimpressionador+davi@gmail.com
20,Shopping Eldorado,Theo,pythonimpressionador+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,pythonimpressionador+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,pythonimpressionador+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,pythonimpressionador+pedro@gmail.com
24,Shopping Barra,Benjamin,pythonimpressionador+benjamin@gmail.com
25,Diretoria,Diretoria,pythonimpressionador+diretoria@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

### Passo 2 - Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [3]:
# incluior o nome da loja em vendas
vendas = vendas.merge(lojas, on = 'ID Loja')
display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,2,2019-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2019-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
...,...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204,Center Shopping Uberlândia
100995,69996,2019-12-26,17,Mochila,4,270,1080,Center Shopping Uberlândia
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87,Center Shopping Uberlândia
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2019-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

In [4]:
dicionario_lojas = {}
for loja in lojas['Loja'] :
    
    dicionario_lojas[loja] = vendas.loc[vendas['Loja'] == loja, :]
display(dicionario_lojas['Rio Mar Recife'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
62,46,2019-01-02,7,Camisa,1,100,100,Rio Mar Recife
63,46,2019-01-02,7,Calça Liso,2,190,380,Rio Mar Recife
64,46,2019-01-02,7,Cinto,1,200,200,Rio Mar Recife
113,87,2019-01-02,7,Camisa Estampa,1,113,113,Rio Mar Recife
142,109,2019-01-02,7,Camisa Gola V Listrado,3,116,348,Rio Mar Recife
...,...,...,...,...,...,...,...,...
100858,69905,2019-12-25,7,Mochila Listrado,2,275,550,Rio Mar Recife
100859,69905,2019-12-25,7,Camisa Xadrez,3,105,315,Rio Mar Recife
100860,69905,2019-12-25,7,Tênis Liso,3,266,798,Rio Mar Recife
100929,69954,2019-12-25,7,Chinelo,3,60,180,Rio Mar Recife
100930,69954,2019-12-25,7,Casaco Listrado,3,269,807,Rio Mar Recife

In [5]:
dia_indicador = vendas['Data'].max()
print(dia_indicador)
print('{}/{}'.format(dia_indicador.day, dia_indicador.month))

2019-12-26 00:00:00
26/12

### Passo 3 - Salvar a planilha na pasta de backup

In [6]:
import pathlib

# Coloque o caminho completo (absoluto) aqui dentro:
caminho_backup = pathlib.Path(r'D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas')

arquivos_pasta_backup = caminho_backup.iterdir()

# Corrigido "arquivos_pasta_backup" sem o 's'
listas_nomes_backup = [arquivo.name for arquivo in arquivos_pasta_backup] 

# for loja in dicionario_lojas: ...

for loja in dicionario_lojas :
    if loja not in listas_nomes_backup :
        nova_pasta = caminho_backup / loja
        nova_pasta.mkdir()

    nome_arquivo = '{}_{}_{}.xlsx'.format(dia_indicador.month, dia_indicador.day,loja)
    local_arquivo = caminho_backup /loja/nome_arquivo
    dicionario_lojas[loja].to_excel(local_arquivo)

12_26_Iguatemi Esplanada.xlsx
12_26_Shopping Midway Mall.xlsx
12_26_Norte Shopping.xlsx
12_26_Shopping Iguatemi Fortaleza.xlsx
12_26_Shopping União de Osasco.xlsx
12_26_Shopping Center Interlagos.xlsx
12_26_Rio Mar Recife.xlsx
12_26_Salvador Shopping.xlsx
12_26_Rio Mar Shopping Fortaleza.xlsx
12_26_Shopping Center Leste Aricanduva.xlsx
12_26_Ribeirão Shopping.xlsx
12_26_Shopping Morumbi.xlsx
12_26_Parque Dom Pedro Shopping.xlsx
12_26_Bourbon Shopping SP.xlsx
12_26_Palladium Shopping Curitiba.xlsx
12_26_Passei das Águas Shopping.xlsx
12_26_Center Shopping Uberlândia.xlsx
12_26_Shopping Recife.xlsx
12_26_Shopping Vila Velha.xlsx
12_26_Shopping SP Market.xlsx
12_26_Shopping Eldorado.xlsx
12_26_Shopping Ibirapuera.xlsx
12_26_Novo Shopping Ribeirão Preto.xlsx
12_26_Iguatemi Campinas.xlsx
12_26_Shopping Barra.xlsx

### Passo 4 - Calcular o indicador para 1 loja

In [8]:
#definição de metas
meta_faturamento_dia = 1000
met_faturamento_ano = 1650000
meta_qtdprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

In [21]:
import win32com.client as win32
import pathlib

# ==========================================
# DEFINIÇÕES INICIAIS (FORA DO LOOP)
# ==========================================

# 1. CRIANDO A LÓGICA DE CORES E ÍCONES:
# Definimos a função fora do 'for' para não criá-la repetidas vezes na memória
def avaliar_meta(valor, meta):
    if valor >= meta:
        return 'green', '▲'  # Verde com seta p/ cima se atingiu/superou a meta
    else:
        return 'red', '▼'    # Vermelho com seta p/ baixo se ficou abaixo da meta

# ==========================================
# INÍCIO DO LOOP PELAS LOJAS
# ==========================================

for loja in dicionario_lojas:
    # --------------------------------------
    # 1. CÁLCULO DOS INDICADORES
    # --------------------------------------
    
    # Aqui você pega o DataFrame da loja de dentro do dicionário
    vendas_loja = dicionario_lojas[loja]

    # CORREÇÃO: Use 'vendas_loja' (que é o DataFrame) para filtrar, não o dicionário
    vendas_loja_dia = vendas_loja.loc[vendas_loja['Data'] == dia_indicador, :]

    # Faturamento
    faturamento_ano = vendas_loja['Valor Final'].sum()
    faturamento_dia = vendas_loja_dia['Valor Final'].sum()

    # Diversidade de produtos
    qtd_produtos_ano = len(vendas_loja['Produto'].unique())
    # CORREÇÃO: Atenção ao nome da variável! Ajustado para 'qtde_produtos_dia' 
    # para bater com a chamada da função 'avaliar_meta' lá embaixo.
    qtd_produtos_dia = len(vendas_loja_dia['Produto'].unique())

    # Ticket medio
    valor_venda = vendas_loja.groupby('Código Venda')[['Valor Final']].sum()
    ticket_medio_ano = valor_venda['Valor Final'].mean()

    valor_venda_dia = vendas_loja_dia.groupby('Código Venda')[['Valor Final']].sum()
    ticket_medio_dia = valor_venda_dia['Valor Final'].mean()

    # --------------------------------------
    # 2. CONFIGURAÇÃO E ENVIO DO E-MAIL
    # --------------------------------------
    
    outlook = win32.gencache.EnsureDispatch('outlook.application')

    
    nome = emails.loc[emails['Loja'] == loja, 'Gerente'].values[0]
    mail = outlook.CreateItem(0)
    mail.To = emails.loc[emails['Loja'] == loja, 'E-mail'].values[0]
    mail.Subject = 'OnePage dia {}/{} - Loja {}'.format(dia_indicador.day, dia_indicador.month, loja)
    
    # Avaliando se bateu a meta para definir cor e ícone do dia
    cor_fat_dia, cenario_fat_dia = avaliar_meta(faturamento_dia, meta_faturamento_dia)
    cor_qtde_dia, cenario_qtde_dia = avaliar_meta(qtd_produtos_dia, meta_qtdprodutos_dia)
    cor_ticket_dia, cenario_ticket_dia = avaliar_meta(ticket_medio_dia, meta_ticketmedio_dia)
    
    # 2. MELHORANDO O VISUAL DO E-MAIL:
    # (Dica: Usei :,.2f para deixar os valores monetários com precisão de 2 casas decimais)
    corpo_email = f'''
    <div style="font-family: Calibri, Arial, sans-serif; color: #333333;">
        <p>Bom dia, <strong>{nome}</strong>!</p>
        <p>O resultado de ontem <strong>({dia_indicador.day}/{dia_indicador.month})</strong> da <strong>Loja {loja}</strong> foi:</p>
        
        <table style="border-collapse: collapse; min-width: 500px; text-align: center; margin-top: 20px;">
          <tr style="background-color: #004d99; color: white;">
            <th style="padding: 10px; border: 1px solid #dddddd;">Indicador</th>
            <th style="padding: 10px; border: 1px solid #dddddd;">Valor Dia</th>
            <th style="padding: 10px; border: 1px solid #dddddd;">Meta Dia</th>
            <th style="padding: 10px; border: 1px solid #dddddd;">Cenário Dia</th>
           </tr>
           
          <tr>
            <td style="padding: 10px; border: 1px solid #dddddd; text-align: left; background-color: #f9f9f9;">Faturamento</td>
            <td style="padding: 10px; border: 1px solid #dddddd; color: {cor_fat_dia}; font-weight: bold;">R$ {faturamento_dia:,.2f}</td>
            <td style="padding: 10px; border: 1px solid #dddddd;">R$ {meta_faturamento_dia:,.2f}</td>
            <td style="padding: 10px; border: 1px solid #dddddd; color: {cor_fat_dia}; font-weight: bold;">{cenario_fat_dia}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #dddddd; text-align: left;">Diversidade de Produtos</td>
            <td style="padding: 10px; border: 1px solid #dddddd; color: {cor_qtde_dia}; font-weight: bold;">{qtde_produtos_dia}</td>
            <td style="padding: 10px; border: 1px solid #dddddd;">{meta_qtdprodutos_dia}</td>
            <td style="padding: 10px; border: 1px solid #dddddd; color: {cor_qtde_dia}; font-weight: bold;">{cenario_qtde_dia}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #dddddd; text-align: left; background-color: #f9f9f9;">Ticket Médio</td>
            <td style="padding: 10px; border: 1px solid #dddddd; color: {cor_ticket_dia}; font-weight: bold;">R$ {ticket_medio_dia:,.2f}</td>
            <td style="padding: 10px; border: 1px solid #dddddd;">R$ {meta_ticketmedio_dia:,.2f}</td>
            <td style="padding: 10px; border: 1px solid #dddddd; color: {cor_ticket_dia}; font-weight: bold;">{cenario_ticket_dia}</td>
          </tr>
        </table>
        
        <p style="margin-top: 25px;">Segue em anexo a planilha com todos os dados para mais detalhes.</p>
        <p>Qualquer dúvida, estou à disposição.</p>
        <p>Att.,<br><strong>Juan</strong></p>
    </div>
    '''
    
    mail.HTMLBody = corpo_email 
    
    # Ajuste no nome do arquivo 
    arquivo_nome = f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'
    
    # Atenção: Garanta que as variáveis "caminho_backup" e "dia_indicador" já estejam definidas acima no seu código original
    caminho_arquivo = pathlib.Path.cwd() / caminho_backup / loja / arquivo_nome
    
    # O SEGREDO DO SUCESSO: Caminho absoluto e .resolve()
    if caminho_arquivo.exists():
        caminho_absoluto = str(caminho_arquivo.resolve())
        print(f"Tentando anexar: {caminho_absoluto}")
        mail.Attachments.Add(caminho_absoluto)
        
        mail.Send()
        print(f"E-mail da loja {loja} enviado com sucesso, amor!")
    else:
        print(f"ERRO: Arquivo não encontrado em {caminho_arquivo}")

Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Iguatemi Esplanada\12_26_Iguatemi Esplanada.xlsx
E-mail da loja Iguatemi Esplanada enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Midway Mall\12_26_Shopping Midway Mall.xlsx
E-mail da loja Shopping Midway Mall enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Norte Shopping\12_26_Norte Shopping.xlsx
E-mail da loja Norte Shopping enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Iguatemi Fortaleza\12_26_Shopping Iguatemi Fortaleza.xlsx
E-mail da loja Shopping Iguatemi Fortaleza enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping União de Osasco\12_26_Shopping União de Osasco.xlsx
E-mail da loja Shopping União de Osasco enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Center Interlagos\12_26_Shopping Center Interlagos.xlsx
E-mail da loja Shopping Center Interlagos enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Rio Mar Recife\12_26_Rio Mar Recife.xlsx
E-mail da loja Rio Mar Recife enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Salvador Shopping\12_26_Salvador Shopping.xlsx
E-mail da loja Salvador Shopping enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Rio Mar Shopping Fortaleza\12_26_Rio Mar Shopping Fortaleza.xlsx
E-mail da loja Rio Mar Shopping Fortaleza enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Center Leste Aricanduva\12_26_Shopping Center Leste Aricanduva.xlsx
E-mail da loja Shopping Center Leste Aricanduva enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Ribeirão Shopping\12_26_Ribeirão Shopping.xlsx
E-mail da loja Ribeirão Shopping enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Morumbi\12_26_Shopping Morumbi.xlsx
E-mail da loja Shopping Morumbi enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Parque Dom Pedro Shopping\12_26_Parque Dom Pedro Shopping.xlsx
E-mail da loja Parque Dom Pedro Shopping enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Bourbon Shopping SP\12_26_Bourbon Shopping SP.xlsx
E-mail da loja Bourbon Shopping SP enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Palladium Shopping Curitiba\12_26_Palladium Shopping Curitiba.xlsx
E-mail da loja Palladium Shopping Curitiba enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Passei das Águas Shopping\12_26_Passei das Águas Shopping.xlsx
E-mail da loja Passei das Águas Shopping enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Center Shopping Uberlândia\12_26_Center Shopping Uberlândia.xlsx
E-mail da loja Center Shopping Uberlândia enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Recife\12_26_Shopping Recife.xlsx
E-mail da loja Shopping Recife enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Vila Velha\12_26_Shopping Vila Velha.xlsx
E-mail da loja Shopping Vila Velha enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping SP Market\12_26_Shopping SP Market.xlsx
E-mail da loja Shopping SP Market enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Eldorado\12_26_Shopping Eldorado.xlsx
E-mail da loja Shopping Eldorado enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Ibirapuera\12_26_Shopping Ibirapuera.xlsx
E-mail da loja Shopping Ibirapuera enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Novo Shopping Ribeirão Preto\12_26_Novo Shopping Ribeirão Preto.xlsx
E-mail da loja Novo Shopping Ribeirão Preto enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Iguatemi Campinas\12_26_Iguatemi Campinas.xlsx
E-mail da loja Iguatemi Campinas enviado com sucesso, amor!
Tentando anexar: D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Shopping Barra\12_26_Shopping Barra.xlsx
E-mail da loja Shopping Barra enviado com sucesso, amor!

### Passo 5 - Enviar por e-mail para o gerente

In [12]:
import pathlib

# Corrigido: fechamento do print, fechamento do format e extensão .xlsx
print(attachment := pathlib.Path.cwd() / caminho_backup / loja / '{}_{}.xlsx'.format(dia_indicador.day, dia_indicador.month))

D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas\Norte Shopping\26_12.xlsx

In [ ]:
# Monta o caminho do arquivo
caminho_arquivo = pathlib.Path.cwd() / caminho_backup / loja / f'{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx'

# O SEGREDO: Verifica se o arquivo existe antes de anexar
if caminho_arquivo.exists():
    print(f"Arquivo encontrado: {caminho_arquivo}")
    mail.Attachments.Add(str(caminho_arquivo))
else:
    print(f"ERRO: O arquivo NÃO foi encontrado em: {caminho_arquivo}")
    # Aqui você pode decidir se quer parar o código ou pular esse envio

com_error: (-2146959355, 'Falha na execução do servidor', None, None)

### Passo 6 - Automatizar todas as lojas

### Passo 7 - Criar ranking para diretoria

In [36]:
faturamento_lojas = vendas.groupby('Loja')[['Loja','Valor Final']].sum()
faturamento_lojas_ano = faturamento_lojas.sort_values(by = 'Valor Final', ascending =  False)
display(faturamento_lojas_ano)

nome_arquivo = '{}_{}_Ranking Anual.xlsx'.format(dia_indicador.month, dia_indicador.day,loja)
faturamento_lojas_ano.to_excel(r'D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas'.format(nome_arquivo))
    

vendas_dia = vendas.loc[vendas['Data']==dia_indicador, : ]
faturamento_lojas_dia = vendas_dia.groupby('Loja')[['Loja','Valor Final']].sum()
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by = 'Valor Final', ascending = False)
display(faturamento_lojas_dia)

nome_arquivo = '{}_{}_Ranking Dia.xlsx'.format(dia_indicador.month, dia_indicador.day,loja)
faturamento_lojas_ano.to_excel(r'D:\Curso Python\Projeto AutomacaoIndicadores\Backup Arquivos Lojas'.format(nome_arquivo))

,Loja,Valor Final
Loja,,
Iguatemi Campinas,Iguatemi CampinasIguatemi CampinasIguatemi Cam...,1762419
Shopping Vila Velha,Shopping Vila VelhaShopping Vila VelhaShopping...,1731167
Bourbon Shopping SP,Bourbon Shopping SPBourbon Shopping SPBourbon ...,1726110
Rio Mar Recife,Rio Mar RecifeRio Mar RecifeRio Mar RecifeRio ...,1722766
Shopping SP Market,Shopping SP MarketShopping SP MarketShopping S...,1721763
Palladium Shopping Curitiba,Palladium Shopping CuritibaPalladium Shopping ...,1721120
Norte Shopping,Norte ShoppingNorte ShoppingNorte ShoppingNort...,1711968
Ribeirão Shopping,Ribeirão ShoppingRibeirão ShoppingRibeirão Sho...,1707122
Iguatemi Esplanada,Iguatemi EsplanadaIguatemi EsplanadaIguatemi E...,1699681
Rio Mar Shopping Fortaleza,Rio Mar Shopping FortalezaRio Mar Shopping For...,1698430
Shopping Center Leste Aricanduva,Shopping Center Leste AricanduvaShopping Cente...,1682870
Novo Shopping Ribeirão Preto,Novo Shopping Ribeirão PretoNovo Shopping Ribe...,1678225
Shopping Iguatemi Fortaleza,Shopping Iguatemi FortalezaShopping Iguatemi F...,1674824
Center Shopping Uberlândia,Center Shopping UberlândiaCenter Shopping Uber...,1668921
Shopping União de Osasco,Shopping União de OsascoShopping União de Osas...,1663770
Shopping Barra,Shopping BarraShopping BarraShopping BarraShop...,1653103
Passei das Águas Shopping,Passei das Águas ShoppingPassei das Águas Shop...,1649014
Shopping Eldorado,Shopping EldoradoShopping EldoradoShopping Eld...,1648111
Salvador Shopping,Salvador ShoppingSalvador ShoppingSalvador Sho...,1646739
Shopping Center Interlagos,Shopping Center InterlagosShopping Center Inte...,1640486
Shopping Ibirapuera,Shopping IbirapueraShopping IbirapueraShopping...,1635060
Parque Dom Pedro Shopping,Parque Dom Pedro ShoppingParque Dom Pedro Shop...,1631630
Shopping Recife,Shopping RecifeShopping RecifeShopping RecifeS...,1624879
Shopping Midway Mall,Shopping Midway MallShopping Midway MallShoppi...,1590441
Shopping Morumbi,Shopping MorumbiShopping MorumbiShopping Morum...,1586444

ValueError: No engine for filetype: ''

### Passo 8 - Enviar e-mail para diretoria

In [37]:
#enviar o e-mail
outlook = win32.Dispatch('outlook.application')

mail = outlook.CreateItem(0)
mail.To = emails.loc[emails['Loja']=='Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {dia_indicador.day}/{dia_indicador.month}'

      mail.Body = f'''
      Prezados, bom dia
      
      Melhor loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[0]} com Faturamento R${faturamento_lojas_dia.iloc[0, 0]}
      Pior loja do Dia em Faturamento: Loja {faturamento_lojas_dia.index[-1]} com Faturamento R${faturamento_lojas_dia.iloc[-1, 0]}
      
      Melhor loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[0]} com Faturamento R${faturamento_lojas_ano.iloc[0, 0]}
      Pior loja do Ano em Faturamento: Loja {faturamento_lojas_ano.index[-1]} com Faturamento R${faturamento_lojas_ano.iloc[-1, 0]}
      
      Segue em anexo os rankings do ano e do dia de todas as lojas.
      
      Qualquer dúvida estou à disposição.
      
      Att.,
      Juan
      '''

# Anexos (pode colocar quantos quiser):
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx'
mail.Attachments.Add(str(attachment))


mail.Send()
print('E-mail da Diretoria enviado')

ValueError: Unknown format code 'f' for object of type 'str'